# <h1><center>Data Processing</center></h1>

In [5]:
#on import pandas et numpy 
import pandas as pd
import numpy as np

In [59]:
#On import notre data frame
pathfile = "C:/Users/Avicii/Desktop/Samad/GI2/Projet de fin d'etude/PredictiveModel/data/data.xlsx"
df = pd.read_excel(pathfile)
df.head()

,Horodateur,sexe,age,logement,filiere,endroit_travail,travail_equipe,heure_dormir,sport_par_sem,activites_para,...,ressources_materials,Mauvais_Gestion_temps,qualite_logement,addiction_drogues,mauvais_choix_de_cours,réseaux_sociaux,Barrieres_de_langage,l'entourage,gaming,Unnamed: 30
0,2020-02-24 22:22:24.019,Homme,21,Interne,GI,Cafè,Non,00:00:00,2 fois,oui,...,Non,Oui,Oui,Non,Non,Non,Oui,Oui,Non,NaN
1,2020-03-05 20:20:16.644,Homme,18,Interne,CP1,La Bibliothèque,Non,02:00:00,5,Oui,...,Oui,Oui,Oui,Non,Oui,Oui,Oui,Non,Oui,NaN
2,2020-03-05 21:08:41.865,Homme,21,Interne,GI,Cafè,Oui,01:00:00,3 fois,Oui,...,Oui,Oui,Oui,Non,Non,Oui,Oui,Non,Oui,NaN
3,2020-03-05 21:38:14.244,Homme,18,Externe,CP2,Cafè,Oui,02:00:00,5,Oui,...,Non,Non,Non,Non,Oui,Oui,Non,Non,Non,NaN
4,2020-03-05 22:39:30.718,Homme,21,Interne,GC,Chez moi,Oui,01:00:00,3 fois,Non,...,Oui,Non,Oui,Non,Non,Non,Oui,Oui,Non,NaN

In [65]:
#determiner les dimensions du dataframe

df.shape

(402, 29)

In [69]:
#show columns 
df.columns

Index(['sexe', 'age', 'logement', 'filiere', 'endroit_travail',
       'travail_equipe ', 'heure_dormir ', 'sport_par_sem', 'activites_para',
       'rythme_formation ', 'compétences_enseignants ',
       'communication_enseignants', 'méthodes_pédagogiques',
       'etat_psychique_preparation ', 'etat_psychique_examen',
       'resultat_etudiant', 'nombre_rattrapage', 'services_bibliothèques',
       'transport_scolaire', 'orientation', 'ressources_materials',
       'Mauvais_Gestion_temps', 'qualite_logement', 'addiction_drogues',
       'mauvais_choix_de_cours', 'réseaux_sociaux', 'Barrieres_de_langage',
       'l'entourage', 'gaming'],
      dtype='object')

In [62]:
#suprimer des headers 
del df['Unnamed: 30']
del df ['Horodateur']

In [70]:
df.head()

,sexe,age,logement,filiere,endroit_travail,travail_equipe,heure_dormir,sport_par_sem,activites_para,rythme_formation,...,orientation,ressources_materials,Mauvais_Gestion_temps,qualite_logement,addiction_drogues,mauvais_choix_de_cours,réseaux_sociaux,Barrieres_de_langage,l'entourage,gaming
0,Homme,21,Interne,GI,Cafè,Non,00:00:00,2 fois,oui,correct,...,Non,Non,Oui,Oui,Non,Non,Non,Oui,Oui,Non
1,Homme,18,Interne,CP1,La Bibliothèque,Non,02:00:00,5,Oui,trop lent,...,Non,Oui,Oui,Oui,Non,Oui,Oui,Oui,Non,Oui
2,Homme,21,Interne,GI,Cafè,Oui,01:00:00,3 fois,Oui,trop lent,...,Non,Oui,Oui,Oui,Non,Non,Oui,Oui,Non,Oui
3,Homme,18,Externe,CP2,Cafè,Oui,02:00:00,5,Oui,correct,...,Non,Non,Non,Non,Non,Oui,Oui,Non,Non,Non
4,Homme,21,Interne,GC,Chez moi,Oui,01:00:00,3 fois,Non,trop lent,...,Oui,Oui,Non,Oui,Non,Non,Non,Oui,Oui,Non

In [75]:
#description 
df.describe(include ="all")

,sexe,age,logement,filiere,endroit_travail,travail_equipe,heure_dormir,sport_par_sem,activites_para,rythme_formation,...,orientation,ressources_materials,Mauvais_Gestion_temps,qualite_logement,addiction_drogues,mauvais_choix_de_cours,réseaux_sociaux,Barrieres_de_langage,l'entourage,gaming
count,402,402.000000,402,401,402,402,402,402,402,402,...,402,402,402,402,402,402,402,402,402,402
unique,2,NaN,2,8,3,2,40,14,3,3,...,2,2,2,2,2,2,2,2,2,2
top,Homme,NaN,Interne,CP1,Chez moi,Non,01:00:00,jamais,Oui,correct,...,Non,Oui,Oui,Oui,Non,Oui,Oui,Non,Oui,Non
freq,232,NaN,231,128,202,247,89,153,203,156,...,240,224,337,208,353,234,225,281,206,315
mean,NaN,20.101990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.431515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,56.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
#clean the the data : exemple age =56 ???
#en remplace la valeur 56 par la moyenne age : mean 
df["age"].value_counts()
df.loc[df["age"]=="56" ,"age"]] = "20"

SyntaxError: invalid syntax (<ipython-input-88-185ad1d88fe0>, line 4)